FROM php:8.4-cli

# Instalar dependências do sistema
RUN apt-get update && apt-get install -y \
    git unzip libzip-dev libpq-dev libssl-dev zlib1g-dev \
    libicu-dev libxml2-dev libcurl4-openssl-dev libpng-dev \
    libjpeg-dev libfreetype6-dev \
    && rm -rf /var/lib/apt/lists/*

# Instalar extensões PHP essenciais
RUN docker-php-ext-install pdo pdo_pgsql pdo_mysql zip gd intl curl opcache

# Instalar PECL extensions
RUN pecl install redis xdebug swoole \
    && docker-php-ext-enable redis xdebug swoole

# Configuração opcional do Xdebug
RUN echo "zend_extension=xdebug.so" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.mode=debug" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.start_with_request=yes" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.client_host=host.docker.internal" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.client_port=9003" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

# Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html
CMD ["php", "-a"]