services:
  app:
    build: ./.docker/php
    container_name: ${PROJECT_NAME}_php
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      PHP_IDE_CONFIG: "serverName=app"
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: ${PROJECT_NAME}_db
      DB_USERNAME: user
      DB_PASSWORD: secret
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - ${PROJECT_NAME}_net

  nginx:
    image: nginx:1.25-alpine
    container_name: ${PROJECT_NAME}_nginx
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - ${PROJECT_NAME}_net

  postgres:
    image: postgres:15-alpine
    container_name: ${PROJECT_NAME}_postgres
    environment:
      POSTGRES_DB: ${PROJECT_NAME}_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d ${PROJECT_NAME}_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ${PROJECT_NAME}_net

  redis:
    container_name: redis-app
    ports:
      - "6379:6379"
    networks:
      - app_net

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit-app
    ports:
      - "8025:8025" # UI
      - "1025:1025" # SMTP
    networks:
      - app_network

  minio:
    image: minio/minio:latest
    container_name: minio-app
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Console Web
    volumes:
      - minio_data:/data
    networks:
      - app_network

networks:
  app_net:

volumes:
  db_data:
  minio_data:
