services:
  app:
    build:
      context: ./docker/php
    container_name: php-app
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db
      - redis
      - minio
      - mailpit
    environment:
      PHP_IDE_CONFIG: "serverName=app"
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
      AWS_DEFAULT_REGION: us-east-1
      AWS_BUCKET: app-bucket
      AWS_ENDPOINT: http://minio:9000
      REDIS_HOST: redis
    networks:
      - app_net

  nginx:
    image: nginx:1.25
    container_name: nginx-app
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - app_net

  db:
    image: postgres:15
    container_name: db-app
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_net

  redis:
    image: redis:7
    container_name: redis-app
    ports:
      - "6379:6379"
    networks:
      - app_net

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit-app
    ports:
      - "8025:8025" # UI
      - "1025:1025" # SMTP
    networks:
      - app_net

  minio:
    image: minio/minio:latest
    container_name: minio-app
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Console Web
    volumes:
      - minio_data:/data
    networks:
      - app_net

networks:
  app_net:

volumes:
  db_data:
  minio_data:
